# 事件列表
events:
  BUY_PRODUCT: 1 # 用户购买产品

# 模块列表
modules:
  user_buy_module: # docker 模块
    class: "\\Zwei\\EventWorkSimple\\Customer\\DemoCustomer" # 调用类
    callback_func: "run" # 调用方法
    listen_events: # 监听事件列表
      - BUY_PRODUCT